# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'date'

default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :deploy_testflight do

    setup_ci(provider: "travis")
    upgrade_app_version

    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true,
      in_house: false
    )

    basic_authorization_token = Base64.strict_encode64("#{ENV["USERNAME"]}:#{ENV["PERSONAL_GITHUB_ACCESS_TOKEN"]}")

    match(
      git_basic_authorization: basic_authorization_token,
      api_key: api_key,
      type: "appstore",
      app_identifier: ["com.tomoki-sun.app.ios.multi-calculator"]
    )

    build_app(
      workspace: "MultiCalculator.xcworkspace",
      scheme: "Production",
      export_options: {
        method: "app-store",
      }
    )

    upload_to_testflight(
      api_key: api_key,
      changelog: `git log -1 --pretty=%B`
    )
  end

  lane :upgrade_app_version do

    today = Date.today
    shortVersionString = "#{today.year}.#{today.month}.#{today.day}"

    set_info_plist_value(
      path: './App/Production/Info.plist',
      key: 'CFBundleShortVersionString',
      value: shortVersionString
    )

    set_info_plist_value(
      path: './App/Production/Info.plist',
      key: 'CFBundleVersion',
      value: `git rev-parse --short HEAD`.to_i(16).to_s
    )
  end
end